name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Python Tests
      id: run-python-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run Python Tests
        setup-command: ''
        command: python tests.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-PYTHON-TESTS_RESULTS: "${{steps.run-python-tests.outputs.result}}"
      with:
        runners: run-python-tests
